[package]
name = "nikikv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
integer-encoding = "3.0.2"    
crc = "1.8"
memmap = "0.7"
log = "0.4.8"
thiserror = "1.0"